[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "NREL-PySAM"
description = "National Laboratory of the Rockies' System Advisor Model Python Wrapper"
readme = {file = "RELEASE.md", content-type = "text/markdown"}
license = "BSD-3-Clause"
authors = [
    {name = "dguittet", email = "dguittet@nlr.gov"},
]
requires-python = ">=3.9"
dependencies = [
    "requests",
]
dynamic = ["version"]
classifiers = [
    "Development Status :: 7 - Inactive",
    "Programming Language :: Python :: 3"
]

[project.urls]
Documentation = "https://nrel-pysam.readthedocs.io"

[tool.setuptools.dynamic]
version = {attr = "PySAM.version.__version__"}

[tool.setuptools.packages.find]
include = ["PySAM*"]

[tool.setuptools.package-data]
PySAM = [
    "*.pyi",
    "*.so",
    "*.so.*",
    "*.dylib",
    "*.dll",
    "*.lib",
    "defaults/*.df",
]
"PySAM.Hybrids" = [
    "*.pyi",
]

[tool.pytest.ini_options]
addopts = "--verbose -s --rootdir=tests"
