name: Test Package

on: [ push ]

jobs:
  build1: 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [ '3.9']
#        python-version: [ '3.9', '3.10', '3.11', '3.12', '3.13', '3.14' ]

    env: 
      BUILD_TYPE: Release
      DEFAULT_BRANCH: develop
      WX_VERSION: '3.2.8.1'
      ORTOOLS_VER: "9.14"
      ORTOOLS_RELEASE: "6206"
  #    SAMNTDIR: ${{ github.workspace }}/../SAM
      NREL_API_KEY: ${{ secrets.NREL_API_KEY }}
      NREL_API_EMAIL: ${{ secrets.NREL_API_EMAIL }}


    name: ${{ matrix.os }} ${{ matrix.python-version }}
    steps:

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: Set relative paths
        shell: bash
        run: | 
            LKDIR=$GITHUB_WORKSPACE/lk
            echo "LKDIR=$LKDIR" >> $GITHUB_ENV
            WEXDIR=$GITHUB_WORKSPACE/wex
            echo "WEXDIR=$WEXDIR" >> $GITHUB_ENV
            SSCDIR=$GITHUB_WORKSPACE/ssc
            echo "SSCDIR=$SSCDIR" >> $GITHUB_ENV
            RAPIDJSONDIR=$GITHUB_WORKSPACE/ssc
            echo "RAPIDJSONDIR=$RAPIDJSONDIR" >> $GITHUB_ENV
            SAMNTDIR=$GITHUB_WORKSPACE/sam
            echo "SAMNTDIR=$SAMNTDIR" >> $GITHUB_ENV
            WXMSW3=$HOME/wx-$WX_VERSION
            echo "WXMSW3=$WXMSW3" >> $GITHUB_ENV
            ORTOOLSDIR=$GITHUB_WORKSPACE/or-tools_x64_VisualStudio2022_cpp_v$ORTOOLS_VER.$ORTOOLS_RELEASE
            echo "ORTOOLSDIR=$ORTOOLSDIR" >> $GITHUB_ENV

      - name: Download OR-Tools
        if: steps.cached-ortools-restore.outputs.cache-hit != 'true'
        shell: bash
        run: |
            curl -L https://github.com/google/or-tools/releases/download/v$ORTOOLS_VER/or-tools_x64_VisualStudio2022_cpp_v$ORTOOLS_VER.$ORTOOLS_RELEASE.zip -o or-tools-$ORTOOLS_VER.zip
            7z x or-tools-$ORTOOLS_VER.zip

      - name: Checkout SAM
        run: |
          cd ..
          git config --global url.https://github.com/.insteadOf git://github.com/
          git clone https://github.com/natlabrockies/SAM.git

      - name: Build SAM_api
        run: |
          cmake -G "Visual Studio 17 2022" -DCMAKE_CONFIGURATION_TYPES="Release" -DSAM_SKIP_TOOLS=1 -DSAM_SKIP_TESTS=1 -DSAM_SKIP_AUTOGEN=0 -DSAMAPI_EXPORT=1 -DUSE_XPRESS=0 -DUSE_COINOR=1 -DCMAKE_SYSTEM_VERSION=10.0 -DCMAKE_SYSTEM_PREFIX_PATH="${ORTOOLSDIR}" -Dabsl_DIR="${ORTOOLSDIR}\lib\cmake\absl" -Dutf8_range_DIR="${ORTOOLSDIR}\lib\cmake\utf8_range" -Dortools_DIR="${ORTOOLSDIR}\lib\cmake\ortools" ..
          msbuild.exe /build Release system_advisor_model.sln /Project SAM_api


      - name: Install conda 
        uses: conda-incubator/setup-miniconda@v4
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}

      - name: Conda info
        shell: bash -el {0}
        run: conda info

      - name: Conda list
        shell: pwsh
        run: conda list

      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Unit tests
        run: |
          source /Users/runner/.bash_profile
          conda activate pysam_env
          pytest tests
