name: Test Package

on: [ push ]

jobs:
  build1: 
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        python-version: [ '3.9', '3.10', '3.11', '3.12', '3.13', '3.14' ]

    env: 
      SAMNTDIR: ${{ github.workspace }}/../SAM
      NREL_API_KEY: ${{ secrets.NREL_API_KEY }}
      NREL_API_EMAIL: ${{ secrets.NREL_API_EMAIL }}

    name: ${{ matrix.os }} ${{ matrix.python-version }}
    steps:
      - name: Install conda 
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: ${{ matrix.python-version }}
          activate-environment: test-env
#          environment-file: environment.yml # Optional: if you have a file
          auto-activate: true

      - name: Verify Conda Installation
        run: |
          conda info
          conda list

